/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Address {
  'city' : string,
  'fullName' : string,
  'mobileNumber' : string,
  'state' : string,
  'address' : string,
  'pincode' : bigint,
}
export interface Booking {
  'bookingId' : bigint,
  'shipment' : ShipmentDetails,
  'sender' : Address,
  'senderPincodeCheck' : PincodeCheckResult,
  'receiverPincodeCheck' : PincodeCheckResult,
  'timestamp' : bigint,
  'receiver' : Address,
}
export interface PincodeCheckResult {
  'isServiceable' : boolean,
  'pincode' : bigint,
}
export interface ShipmentDetails {
  'weight' : bigint,
  'paymentType' : { 'cod' : null } |
    { 'prepaid' : null },
  'dimensions' : [] | [string],
}
export interface _SERVICE {
  'bookShipment' : ActorMethod<[Address, Address, ShipmentDetails], bigint>,
  'getAllBookings' : ActorMethod<[], Array<Booking>>,
  'trackShipment' : ActorMethod<[bigint], Booking>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];