/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Address = IDL.Record({
  'city' : IDL.Text,
  'fullName' : IDL.Text,
  'mobileNumber' : IDL.Text,
  'state' : IDL.Text,
  'address' : IDL.Text,
  'pincode' : IDL.Nat,
});
export const ShipmentDetails = IDL.Record({
  'weight' : IDL.Nat,
  'paymentType' : IDL.Variant({ 'cod' : IDL.Null, 'prepaid' : IDL.Null }),
  'dimensions' : IDL.Opt(IDL.Text),
});
export const PincodeCheckResult = IDL.Record({
  'isServiceable' : IDL.Bool,
  'pincode' : IDL.Nat,
});
export const Booking = IDL.Record({
  'bookingId' : IDL.Nat,
  'shipment' : ShipmentDetails,
  'sender' : Address,
  'senderPincodeCheck' : PincodeCheckResult,
  'receiverPincodeCheck' : PincodeCheckResult,
  'timestamp' : IDL.Int,
  'receiver' : Address,
});

export const idlService = IDL.Service({
  'bookShipment' : IDL.Func([Address, Address, ShipmentDetails], [IDL.Nat], []),
  'getAllBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'trackShipment' : IDL.Func([IDL.Nat], [Booking], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Address = IDL.Record({
    'city' : IDL.Text,
    'fullName' : IDL.Text,
    'mobileNumber' : IDL.Text,
    'state' : IDL.Text,
    'address' : IDL.Text,
    'pincode' : IDL.Nat,
  });
  const ShipmentDetails = IDL.Record({
    'weight' : IDL.Nat,
    'paymentType' : IDL.Variant({ 'cod' : IDL.Null, 'prepaid' : IDL.Null }),
    'dimensions' : IDL.Opt(IDL.Text),
  });
  const PincodeCheckResult = IDL.Record({
    'isServiceable' : IDL.Bool,
    'pincode' : IDL.Nat,
  });
  const Booking = IDL.Record({
    'bookingId' : IDL.Nat,
    'shipment' : ShipmentDetails,
    'sender' : Address,
    'senderPincodeCheck' : PincodeCheckResult,
    'receiverPincodeCheck' : PincodeCheckResult,
    'timestamp' : IDL.Int,
    'receiver' : Address,
  });
  
  return IDL.Service({
    'bookShipment' : IDL.Func(
        [Address, Address, ShipmentDetails],
        [IDL.Nat],
        [],
      ),
    'getAllBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'trackShipment' : IDL.Func([IDL.Nat], [Booking], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };