/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface ShipmentDetails {
    weight: bigint;
    paymentType: Variant_cod_prepaid;
    dimensions?: string;
}
export interface Booking {
    bookingId: bigint;
    shipment: ShipmentDetails;
    sender: Address;
    senderPincodeCheck: PincodeCheckResult;
    receiverPincodeCheck: PincodeCheckResult;
    timestamp: bigint;
    receiver: Address;
}
export interface PincodeCheckResult {
    isServiceable: boolean;
    pincode: bigint;
}
export interface Address {
    city: string;
    fullName: string;
    mobileNumber: string;
    state: string;
    address: string;
    pincode: bigint;
}
export enum Variant_cod_prepaid {
    cod = "cod",
    prepaid = "prepaid"
}
export interface backendInterface {
    bookShipment(sender: Address, receiver: Address, shipment: ShipmentDetails): Promise<bigint>;
    getAllBookings(): Promise<Array<Booking>>;
    trackShipment(bookingId: bigint): Promise<Booking>;
}
import type { Address as _Address, Booking as _Booking, PincodeCheckResult as _PincodeCheckResult, ShipmentDetails as _ShipmentDetails } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async bookShipment(arg0: Address, arg1: Address, arg2: ShipmentDetails): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.bookShipment(arg0, arg1, to_candid_ShipmentDetails_n1(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.bookShipment(arg0, arg1, to_candid_ShipmentDetails_n1(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async getAllBookings(): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllBookings();
                return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllBookings();
            return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async trackShipment(arg0: bigint): Promise<Booking> {
        if (this.processError) {
            try {
                const result = await this.actor.trackShipment(arg0);
                return from_candid_Booking_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.trackShipment(arg0);
            return from_candid_Booking_n5(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_Booking_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Booking): Booking {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_ShipmentDetails_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ShipmentDetails): ShipmentDetails {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bookingId: bigint;
    shipment: _ShipmentDetails;
    sender: _Address;
    senderPincodeCheck: _PincodeCheckResult;
    receiverPincodeCheck: _PincodeCheckResult;
    timestamp: bigint;
    receiver: _Address;
}): {
    bookingId: bigint;
    shipment: ShipmentDetails;
    sender: Address;
    senderPincodeCheck: PincodeCheckResult;
    receiverPincodeCheck: PincodeCheckResult;
    timestamp: bigint;
    receiver: Address;
} {
    return {
        bookingId: value.bookingId,
        shipment: from_candid_ShipmentDetails_n7(_uploadFile, _downloadFile, value.shipment),
        sender: value.sender,
        senderPincodeCheck: value.senderPincodeCheck,
        receiverPincodeCheck: value.receiverPincodeCheck,
        timestamp: value.timestamp,
        receiver: value.receiver
    };
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    weight: bigint;
    paymentType: {
        cod: null;
    } | {
        prepaid: null;
    };
    dimensions: [] | [string];
}): {
    weight: bigint;
    paymentType: Variant_cod_prepaid;
    dimensions?: string;
} {
    return {
        weight: value.weight,
        paymentType: from_candid_variant_n9(_uploadFile, _downloadFile, value.paymentType),
        dimensions: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.dimensions))
    };
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cod: null;
} | {
    prepaid: null;
}): Variant_cod_prepaid {
    return "cod" in value ? Variant_cod_prepaid.cod : "prepaid" in value ? Variant_cod_prepaid.prepaid : value;
}
function from_candid_vec_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Booking>): Array<Booking> {
    return value.map((x)=>from_candid_Booking_n5(_uploadFile, _downloadFile, x));
}
function to_candid_ShipmentDetails_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ShipmentDetails): _ShipmentDetails {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    weight: bigint;
    paymentType: Variant_cod_prepaid;
    dimensions?: string;
}): {
    weight: bigint;
    paymentType: {
        cod: null;
    } | {
        prepaid: null;
    };
    dimensions: [] | [string];
} {
    return {
        weight: value.weight,
        paymentType: to_candid_variant_n3(_uploadFile, _downloadFile, value.paymentType),
        dimensions: value.dimensions ? candid_some(value.dimensions) : candid_none()
    };
}
function to_candid_variant_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_cod_prepaid): {
    cod: null;
} | {
    prepaid: null;
} {
    return value == Variant_cod_prepaid.cod ? {
        cod: null
    } : value == Variant_cod_prepaid.prepaid ? {
        prepaid: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
